export  const divisionData = {
    default: {
      name: "White Aluminium Enterprises LLC",
      emails: ["info@whitealuminium.ae", "fab@whitealuminium.ae"],
      phones: ["+971 2 5500 830", "+971 2 5555 423"],
      fax: "+971 2 5559 847",
      timings: {
        weekday: "Monday to Saturday",
        weekdayTime: "7:00 AM - 5:00 PM",
        friday: "Friday",
        fridayTime: "7:00 AM - 12:00 PM & 2:00 PM - 5:00 PM",
        sunday: "Sunday",
        sundayTime: "Closed",
      },
      socialLinks: {
        facebook: "https://www.facebook.com/whitealuminiumglassdivision",
        instagram: "https://www.instagram.com/whiteglassdivision/",
        linkedin: "https://www.linkedin.com/company/white-aluminium-enterprises/",
      },
    },
    GlassDivision: {
      id: "glass",
      name: "White Aluminium - Glass Division",
      emails: ["info@whitealuminium.ae", "itsupport@whitealuminium.ae"],
      phones: ["+971 2 5500 830", "+971 2 5555 423"],
      fax: "+971 2 5500 828",
      mapLocation: "https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d232416.64975559275!2d54.214623441538606!3d24.467774843069183!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x3e5e663873b8e163%3A0xbdec54c8cf87afee!2sWhite%20Aluminium%20Kitchen!5e0!3m2!1sen!2sae!4v1737396748718!5m2!1sen!2sae",
      timings: {
        weekday: "Monday to Saturday",
        weekdayTime: "7:00 AM - 5:00 PM",
        friday: "Friday",
        fridayTime: "7:00 AM - 12:00 PM & 2:00 PM - 5:00 PM",
        sunday: "Sunday",
        sundayTime: "Closed",
      },
      socialLinks: {
        facebook: "https://www.facebook.com/whitealuminiumglassdivision",
        instagram: "https://www.instagram.com/whiteglassdivision/",
        linkedin: "https://www.linkedin.com/company/white-aluminium-enterprises/",
      },
    },
    ArchitecturalAluminium: {
      name: "White Aluminium - Architectural Aluminium",
      emails: ["fab@whitealuminium.ae", "itsupport@whitealuminium.ae"],
      phones: ["+971 2 5541 889", "+971 2 5500 830"],
      fax: "+971 2 5545 262",
      timings: {
        weekday: "Monday to Saturday",
        weekdayTime: "7:00 AM - 5:00 PM",
        friday: "Friday",
        fridayTime: "7:00 AM - 12:00 PM & 2:00 PM - 5:00 PM",
        sunday: "Sunday",
        sundayTime: "Closed",
      },
      socialLinks: {
        facebook: "https://www.facebook.com/WhiteAluminium",
        instagram: "https://www.instagram.com/WhiteAluminium",
        linkedin: "https://www.linkedin.com/company/white-aluminium-enterprises/",
      },
    },
    CommercialDivision: {
      name: "White Aluminium - Commercial Division",
      emails: ["info.ho@whitealuminium.ae", "itsupport@whitealuminium.ae"],
      phones: ["+971 2 5555 423", "+971 2 5500 830"],
      fax: "+971 2 5559 847",
      timings: {
        weekday: "Monday to Saturday",
        weekdayTime: "7:00 AM - 5:00 PM",
        friday: "Friday",
        fridayTime: "7:00 AM - 12:00 PM & 2:00 PM - 5:00 PM",
        sunday: "Sunday",
        sundayTime: "Closed",
      },
      socialLinks: {
        facebook: "https://www.facebook.com/people/White-Aluminium-Enterprises-LLC-Commercial-Division/100068555354640/",
        instagram: "https://www.instagram.com/whitecommercialdivision/",
        linkedin: "https://www.linkedin.com/company/white-aluminium-enterprises/",
      },
    },
    KitchenDivision: {
      name: "White Aluminium - Kitchen Division",
      emails: ["kitchen@whitealuminium.ae", "itsupport@whitealuminium.ae"],
      phones: ["+971 2 6426 700", "+971 2 5500 830"],
      fax: "+971 2 6423 572",
      timings: {
        weekday: "Saturday to Thursday",
        weekdayTime: "8:30 AM - 5:00 PM | ",
        friday: "Friday",
        fridayTime: "Closed",
        sunday: "",
        sundayTime: "",
      },
      socialLinks: {
        facebook: "https://www.facebook.com/Aluminiumkitchenpantrywardrobes",
        instagram: "https://www.instagram.com/whitealuminiumkitchens",
        linkedin: "https://www.linkedin.com/company/white-aluminium-enterprises/",
      },
    },
    AutomaticEntrance: {
      name: "White Aluminium - Automatic Entrance",
      emails: ["info@whitealuminium.ae", "itsupport@whitealuminium.ae"],
      phones: ["+971 2 5551 690", "+971 2 5500 830"],
      fax: "+971 2 5551 691",
      timings: {
        weekday: "Monday to Saturday",
        weekdayTime: "7:00 AM - 5:00 PM",
        friday: "Friday",
        fridayTime: "7:00 AM - 12:00 PM & 2:00 PM - 5:00 PM",
        sunday: "Sunday",
        sundayTime: "Closed",
      },
      socialLinks: {
        facebook: "https://www.facebook.com/WhiteAluminium",
        instagram: "https://www.instagram.com/WhiteAluminium",
        linkedin: "https://www.linkedin.com/company/white-aluminium-enterprises/",
      },
    },
    FireRatedGlazedDoors: {
      name: "White Aluminium - Fire Rated Glazed Doors & Facades",
      emails: ["asif@whitealuminium.ae", "fab@whitealuminium.ae"],
      phones: ["+971 2 5541 889", "+971 50 8298 071"],
      fax: "+971 2 5545 262",
      timings: {
        weekday: "Monday to Saturday",
        weekdayTime: "7:00 AM - 5:00 PM",
        friday: "Friday",
        fridayTime: "7:00 AM - 12:00 PM & 2:00 PM - 5:00 PM",
        sunday: "Sunday",
        sundayTime: "Closed",
      },
      socialLinks: {
        facebook: "https://www.facebook.com/people/White-Aluminium-Enterprises-LLC-Fire-Rated-Glazed-Division/100076141713122/",
        instagram: "https://www.instagram.com/whitefirerateddivision/",
        linkedin: "https://www.linkedin.com/company/white-aluminium-enterprises/",
      },
    },
  };